<!-- html -->
<template>
  <m-space :size="[10, 10]">
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
    <m-button>按钮</m-button>
  </m-space>
</template>